# Generated by Django 4.1.1 on 2022-09-24 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_resetpassword_expire_at_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2022, 9, 24, 6, 39, 49, 656597, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
