# Generated by Django 4.1.1 on 2022-10-01 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_forgotpassword_delete_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 8, 23, 17, 19218, tzinfo=datetime.timezone.utc)),
        ),
    ]
